# plpgsql-workbench — Platform Makefile
#
# Quick start:
#   make dev-up        Start dev stack (postgres + postgrest + nginx)
#   npm run dev        Start MCP server (port 3100, separate terminal)
#   make dev-init      First time: load all modules into DB
#
# Daily:
#   make dev-sync      Push frontend assets to nginx after JS/CSS changes
#   make dev-down      Stop stack (data preserved)
#   make dev-clean     Stop stack + clean frontend (data preserved)
#
# Apps:
#   make app-up APP=uxlab    Start an app stack
#   make app-down APP=uxlab  Stop an app stack

PGV_IMAGE := pg-workbench

# --- Docker image (postgres + postgis + plpgsql_check + pgtap) ---

.PHONY: image

image: ## Build pg-workbench Docker image (if not exists)
	@docker image inspect $(PGV_IMAGE) > /dev/null 2>&1 || \
		(echo "Building $(PGV_IMAGE)..." && docker build -t $(PGV_IMAGE) docker/)

# --- Dev stack (postgres:5433 + postgrest:3000 + nginx:8080) ---

.PHONY: dev-up dev-down dev-clean dev-init dev-sync

dev-up: image dev-env ## Start dev stack: postgres:5433, postgrest:3000, nginx:8080
	docker compose up -d
	@echo ""
	@echo "  postgres  → localhost:5433"
	@echo "  postgrest → localhost:3000  (schemas: $$(cat .env 2>/dev/null | grep PGRST_DB_SCHEMAS | cut -d= -f2))"
	@echo "  frontend  → http://localhost:8080"

dev-env: # (internal) Generate .env with PGRST_DB_SCHEMAS from module.json files
	@schemas=$$(python3 -c "import json,glob; \
		s=[]; \
		[s.extend([p, p+'_ut']) for f in sorted(glob.glob('modules/*/module.json')) \
		 for p in [json.load(open(f)).get('schemas',{}).get('public','')] if p]; \
		s.sort(key=lambda x: (0 if x.startswith('pgv') else 1, x)); \
		print(','.join(s))" 2>/dev/null || echo "pgv"); \
	echo "PGRST_DB_SCHEMAS=$$schemas" > .env

dev-down: ## Stop dev stack (data preserved in data/pgdata/)
	docker compose down

dev-clean: ## Stop stack + clean frontend assets (data preserved)
	docker compose down
	@rm -rf dev/frontend/*
	@echo "Data preserved in data/pgdata/ — delete manually if needed"

dev-sync: ## Copy modules/*/frontend/* to dev/frontend/ for nginx
	@echo "Syncing module assets → dev/frontend/"
	@mkdir -p dev/frontend
	@for mod in modules/*/; do \
		if [ -d "$$mod/frontend" ]; then \
			cp -r "$$mod/frontend/"* dev/frontend/ 2>/dev/null || true; \
		fi; \
	done
	@echo "Generating pgv-modules.js..."
	@python3 -c "\
	import json, glob; \
	scripts = []; styles = []; \
	[scripts.extend(a.get('scripts',[])) or styles.extend(a.get('styles',[])) \
	 for f in sorted(glob.glob('modules/*/module.json')) \
	 for a in [json.load(open(f)).get('assets',{})]]; \
	lines = ['// Auto-generated by make dev-sync — DO NOT EDIT', '// document.write ensures scripts load synchronously before Alpine (defer)']; \
	[lines.append('document.write(\\'<link rel=\"stylesheet\" href=\"/%s\">\\');' % s.split('/')[-1]) for s in styles]; \
	[lines.append('document.write(\\'<script src=\"/%s\"><\\\\/script>\\');' % s.split('/')[-1]) for s in scripts]; \
	open('dev/frontend/pgv-modules.js','w').write('\n'.join(lines)+'\n')"
	@echo "Generating dev index..."
	@python3 -c "\
	import json, glob; \
	mods = []; \
	[mods.append({'schema': m.get('schemas',{}).get('public',''), 'name': m.get('name','?'), 'desc': m.get('description','')}) \
	 for f in sorted(glob.glob('modules/*/module.json')) \
	 for m in [json.load(open(f))] \
	 if m.get('schemas',{}).get('public')]; \
	links = ''.join('<li><a href=\"/%s/\">%s</a><br><small>%s</small></li>' % (m['schema'], m['name'], m['desc']) for m in mods); \
	print('<!DOCTYPE html><html lang=fr data-theme=light><head><meta charset=utf-8><meta name=viewport content=\"width=device-width,initial-scale=1\"><title>Dev — Modules</title><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css><link rel=stylesheet href=/pgview.css></head><body><main class=container><hgroup><h2>Dev — Modules</h2><p>Choisir un module</p></hgroup><ul>%s</ul></main></body></html>' % links)" \
	> dev/frontend/dev-index.html
	@echo "Done"

dev-init: dev-up dev-sync ## First start: load all build/*.sql into dev DB
	@echo "Waiting for DB..."
	@sleep 2
	@for mod in modules/*/; do \
		for sql in "$$mod"build/*.sql; do \
			[ -f "$$sql" ] && echo "  Loading $$sql" && \
			PGPASSWORD=postgres psql -h localhost -p 5433 -U postgres -f "$$sql" -q 2>&1 | grep -v "^$$" || true; \
		done; \
	done
	@echo "Creating QA schemas..."
	@for mod in modules/*/; do \
		schema=$$(python3 -c "import json; print(json.load(open('$${mod}module.json')).get('schemas',{}).get('qa',''))" 2>/dev/null); \
		if [ -n "$$schema" ]; then \
			echo "  CREATE SCHEMA $$schema"; \
			PGPASSWORD=postgres psql -h localhost -p 5433 -U postgres -c \
				"CREATE SCHEMA IF NOT EXISTS $$schema; GRANT USAGE ON SCHEMA $$schema TO web_anon; GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA $$schema TO web_anon;" -q 2>&1 | grep -v "^$$" || true; \
		fi; \
	done
	@echo "Loading QA seeds..."
	@for mod in modules/*/; do \
		if [ -f "$${mod}qa/seed.sql" ]; then \
			echo "  Loading $${mod}qa/seed.sql" && \
			PGPASSWORD=postgres psql -h localhost -p 5433 -U postgres -f "$${mod}qa/seed.sql" -q 2>&1 | grep -v "^$$" || true; \
		fi; \
	done
	@echo "All modules loaded into dev DB"

# --- App management (make app-up APP=name) ---

.PHONY: app-up app-down app-clean app-logs

app-up: ## Start app stack (APP=name required)
	@test -n "$(APP)" || (echo "Usage: make app-up APP=uxlab" && exit 1)
	$(MAKE) -C apps/$(APP) up

app-down: ## Stop app stack
	@test -n "$(APP)" || (echo "Usage: make app-down APP=uxlab" && exit 1)
	$(MAKE) -C apps/$(APP) down

app-clean: ## Stop + clean app stack
	@test -n "$(APP)" || (echo "Usage: make app-clean APP=uxlab" && exit 1)
	$(MAKE) -C apps/$(APP) clean

app-logs: ## Tail app logs
	@test -n "$(APP)" || (echo "Usage: make app-logs APP=uxlab" && exit 1)
	$(MAKE) -C apps/$(APP) logs

# --- Sync modules to all apps ---

.PHONY: sync-modules

sync-modules: ## Run pgm install in every app
	@for app in apps/*/; do \
		if [ -f "$$app/workbench.json" ]; then \
			echo "Syncing modules → $$app"; \
			(cd "$$app" && node ../../dist/pgm/cli.js app install) || true; \
		fi; \
	done

# --- Agents (one tmux session per module, running claude) ---

STRIP_VARS := CLAUDECODE CLAUDE_CODE_ENTRYPOINT CLAUDE_CODE_SESSION_ID \
	CLAUDE_CODE_CONVERSATION_ID CLAUDE_CODE_TASK_ID \
	NON_INTERACTIVE MCP_TRANSPORT MCP_SESSION_ID

.PHONY: agents agents-kill agents-restart

agents: ## Spawn Claude agents (one tmux session per module)
	@for mod in modules/*/; do \
		name=$$(basename "$$mod"); \
		if tmux has-session -t "$$name" 2>/dev/null; then \
			echo "  OK    $$name (already running)"; \
		else \
			printf '#!/bin/sh\nunset $(STRIP_VARS)\nexec claude\n' > "/tmp/pgw-spawn-$$name.sh"; \
			chmod 700 "/tmp/pgw-spawn-$$name.sh"; \
			tmux new-session -d -s "$$name" -c "$$mod" "/tmp/pgw-spawn-$$name.sh"; \
			tmux set-option -t "$$name" history-limit 50000 2>/dev/null || true; \
			tmux set-option -t "$$name" remain-on-exit on 2>/dev/null || true; \
			echo "  START $$name"; \
		fi; \
	done

agents-kill: ## Kill all agent tmux sessions
	@for mod in modules/*/; do \
		name=$$(basename "$$mod"); \
		if tmux has-session -t "$$name" 2>/dev/null; then \
			tmux kill-session -t "$$name"; \
			rm -f "/tmp/pgw-tmux-$$name.log" "/tmp/pgw-spawn-$$name.sh"; \
			echo "  KILL  $$name"; \
		fi; \
	done

agents-restart: agents-kill agents ## Kill then respawn all agents

# --- Build ---

.PHONY: build check help

build: ## Compile TypeScript (tsc → dist/)
	npm run build

check: ## Type-check without emitting
	npx tsc --noEmit

# --- Help ---

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*##' $(MAKEFILE_LIST) | \
		awk -F ':.*## ' '{printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'
