/**
 * pgm scaffold — generates app and module files.
 * Apps get docker-compose, Makefile, nginx, roles, MCP config.
 * Modules get module.json, sql/, frontend/, MCP config for dev DB.
 */

import fs from "node:fs/promises";
import path from "node:path";
import type { AppConfig } from "./resolver.js";

interface Ports {
  pg: number;
  pgrst: number;
  http: number;
  mcp: number;
}

// --- Port auto-assignment ---

export async function findNextPorts(wsRoot: string): Promise<Ports> {
  const appsDir = path.join(wsRoot, "apps");
  const used: Ports[] = [];

  try {
    const entries = await fs.readdir(appsDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const configPath = path.join(appsDir, entry.name, "workbench.json");
      try {
        const raw = await fs.readFile(configPath, "utf-8");
        const config = JSON.parse(raw) as AppConfig & { ports?: Ports };
        if (config.ports) {
          used.push(config.ports);
        } else if (config.connection) {
          // Parse port from connection string
          const m = config.connection.match(/:(\d+)\//);
          if (m) {
            const pg = parseInt(m[1], 10);
            used.push({ pg, pgrst: pg - 2440, http: pg + 2640, mcp: pg - 2340 });
          }
        }
      } catch {
        // skip
      }
    }
  } catch {
    // apps/ doesn't exist yet
  }

  // Find next available slot (starting from 1)
  for (let n = 1; n < 100; n++) {
    const candidate: Ports = {
      pg: 5440 + n,
      pgrst: 3000 + n,
      http: 8080 + n,
      mcp: 3100 + n,
    };
    const conflict = used.some(
      (u) =>
        u.pg === candidate.pg || u.pgrst === candidate.pgrst || u.http === candidate.http || u.mcp === candidate.mcp,
    );
    if (!conflict) return candidate;
  }

  throw new Error("Cannot find available ports");
}

// --- Scaffold ---

export async function scaffoldApp(appDir: string, name: string, ports: Ports, wsRoot: string): Promise<string[]> {
  const created: string[] = [];
  const dirName = path.basename(appDir);

  await fs.mkdir(path.join(appDir, "sql"), { recursive: true });
  await fs.mkdir(path.join(appDir, "frontend"), { recursive: true });
  await fs.mkdir(path.join(appDir, ".claude"), { recursive: true });

  // workbench.json
  const config: AppConfig & { ports: Ports } = {
    name,
    modules: ["pgv"],
    packs: ["plpgsql"],
    connection: `postgresql://postgres:postgres@localhost:${ports.pg}/postgres`,
    port: ports.mcp,
    ports,
  };
  await fs.writeFile(path.join(appDir, "workbench.json"), `${JSON.stringify(config, null, 2)}\n`);
  created.push("workbench.json");

  // .env (initial — will be regenerated by pgm app install)
  await fs.writeFile(path.join(appDir, ".env"), `PGRST_DB_SCHEMAS=${name}\n`);
  created.push(".env");

  // docker-compose.yml
  await fs.writeFile(path.join(appDir, "docker-compose.yml"), dockerCompose(name, ports));
  created.push("docker-compose.yml");

  // Makefile
  const relPath = path.relative(appDir, wsRoot);
  await fs.writeFile(path.join(appDir, "Makefile"), makefile(dirName, ports, relPath));
  created.push("Makefile");

  // sql/01-roles.sql
  await fs.writeFile(path.join(appDir, "sql", "01-roles.sql"), rolesSql(name));
  created.push("sql/01-roles.sql");

  // frontend/nginx.conf
  await fs.writeFile(path.join(appDir, "frontend", "nginx.conf"), nginxConf(ports));
  created.push("frontend/nginx.conf");

  // .mcp.json
  await fs.writeFile(path.join(appDir, ".mcp.json"), mcpJson(ports));
  created.push(".mcp.json");

  // .claude/settings.local.json
  await fs.writeFile(path.join(appDir, ".claude", "settings.local.json"), claudeSettings(name, ports));
  created.push(".claude/settings.local.json");

  return created;
}

// --- Templates ---

function dockerCompose(name: string, ports: Ports): string {
  // Use literal ${...} in the YAML — these are docker-compose env substitutions, not JS
  return `# ${name} — PG:${ports.pg} PGRST:${ports.pgrst} HTTP:${ports.http}
services:
  postgres:
    image: pg-workbench
    ports:
      - "${ports.pg}:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

  postgrest:
    image: postgrest/postgrest:v12.2.3
    ports:
      - "${ports.pgrst}:3000"
    env_file: .env
    environment:
      PGRST_DB_URI: postgres://authenticator:authenticator@postgres:5432/postgres
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_EXTRA_SEARCH_PATH: public,pgv
      PGRST_DB_CHANNEL_ENABLED: "true"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    ports:
      - "${ports.http}:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - postgrest
`;
}

function makefile(name: string, ports: Ports, relPath: string): string {
  const pgmCli = `node ${relPath}/dist/pgm/cli.js`;
  return `# ${name} — PG:${ports.pg} PGRST:${ports.pgrst} HTTP:${ports.http}
COMPOSE := docker compose

.PHONY: up down init clean logs ps sync deploy reload mcp image

image:
\t@docker image inspect pg-workbench > /dev/null 2>&1 || \\
\t\t(echo "Building pg-workbench..." && docker build -t pg-workbench ${relPath}/docker/)

sync:
\t${pgmCli} app install

up: image sync
\t$(COMPOSE) up -d
\t@echo ""
\t@echo "  postgres  → localhost:${ports.pg}"
\t@echo "  postgrest → localhost:${ports.pgrst}  (schemas: $$(grep PGRST_DB_SCHEMAS .env 2>/dev/null | cut -d= -f2))"
\t@echo "  frontend  → http://localhost:${ports.http}"

init: clean up
\t@echo "Fresh start complete"

down:
\t$(COMPOSE) down

clean:
\t$(COMPOSE) down -v

deploy:
\t${pgmCli} app deploy --apply

reload: sync
\t@PGPASSWORD=postgres psql -h localhost -p ${ports.pg} -U postgres \\
\t\t-c "SELECT pg_notify('pgrst', 'reload schema')" -q 2>&1 && \\
\t\techo "PostgREST schema cache reloaded" || true

logs:
\t$(COMPOSE) logs -f

ps:
\t$(COMPOSE) ps

mcp:
\tcd ${relPath} && WORKBENCH_MODE=dev WORKBENCH_CONFIG=apps/${name}/workbench.json npx nodemon --watch src --ext ts --exec 'node --import tsx src/index.ts'
`;
}

function rolesSql(_name: string): string {
  return `-- Roles and domain (module schemas are created by their own DDL files)
DO $$ BEGIN CREATE DOMAIN "text/html" AS TEXT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'authenticator'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE anon NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
GRANT anon TO authenticator;
`;
}

function nginxConf(ports: Ports): string {
  return `server {
    listen 80;

    gzip on;
    gzip_types text/html text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /rpc/ {
        proxy_pass http://postgrest:3000/rpc/;
        proxy_set_header Host $host;
        proxy_set_header Accept $http_accept;
    }

    location /api/ {
        proxy_pass http://host.docker.internal:${ports.mcp}/api/;
        proxy_set_header Host $host;
    }
}
`;
}

function mcpJson(ports: Ports): string {
  return `${JSON.stringify(
    {
      mcpServers: {
        "plpgsql-workbench": {
          type: "http",
          url: `http://localhost:${ports.mcp}/mcp`,
        },
      },
    },
    null,
    2,
  )}\n`;
}

function claudeSettings(appName: string, ports: Ports): string {
  return `${JSON.stringify(
    {
      permissions: {
        allow: [
          "Bash(git:*)",
          "Bash(make:*)",
          "Bash(docker compose:*)",
          "mcp__plpgsql-workbench__pg_query",
          "mcp__plpgsql-workbench__pg_get",
          "mcp__plpgsql-workbench__pg_func_set",
          "mcp__plpgsql-workbench__pg_func_edit",
          "mcp__plpgsql-workbench__pg_func_save",
          "mcp__plpgsql-workbench__pg_func_load",
          "mcp__plpgsql-workbench__pg_test",
          "mcp__plpgsql-workbench__pg_explain",
          "mcp__plpgsql-workbench__pg_search",
          "mcp__plpgsql-workbench__pg_schema",
          "mcp__plpgsql-workbench__pg_pack",
          "mcp__plpgsql-workbench__pg_coverage",
          "mcp__plpgsql-workbench__pg_doc",
          "mcp__plpgsql-workbench__pg_msg",
          "mcp__plpgsql-workbench__pg_msg_inbox",
          "mcp__plpgsql-workbench__pg_preview",
        ],
      },
      enableAllProjectMcpServers: true,
      enabledMcpjsonServers: ["plpgsql-workbench"],
      hooks: {
        SessionStart: [
          {
            matcher: "startup|resume",
            hooks: [
              {
                type: "http",
                url: `http://localhost:${ports.mcp}/hooks/${appName}/session`,
                timeout: 5,
              },
            ],
          },
        ],
        PreToolUse: [
          {
            matcher:
              "mcp__plpgsql-workbench__pg_query|mcp__plpgsql-workbench__pg_func_set|mcp__plpgsql-workbench__pg_func_edit|Write|Edit",
            hooks: [
              {
                type: "http",
                url: `http://localhost:${ports.mcp}/hooks/${appName}`,
                timeout: 5,
              },
            ],
          },
        ],
      },
    },
    null,
    2,
  )}\n`;
}

// ── Module scaffold ──────────────────────────────────────────────

export async function scaffoldModule(
  moduleDir: string,
  name: string,
  schemaName: string,
  mcpPort: number,
  description?: string,
): Promise<string[]> {
  const created: string[] = [];

  await fs.mkdir(path.join(moduleDir, "build"), { recursive: true });
  await fs.mkdir(path.join(moduleDir, "src"), { recursive: true });
  await fs.mkdir(path.join(moduleDir, "qa"), { recursive: true });
  await fs.mkdir(path.join(moduleDir, "frontend"), { recursive: true });
  await fs.mkdir(path.join(moduleDir, ".claude"), { recursive: true });

  // module.json
  const manifest = {
    name,
    version: "0.1.0",
    description: description ?? "",
    schemas: { public: schemaName, private: null, qa: `${schemaName}_qa` },
    dependencies: ["pgv"],
    extensions: [],
    sql: [`build/${schemaName}.ddl.sql`, `build/${schemaName}.func.sql`],
    assets: { frontend: [], scripts: [], styles: [] },
    grants: { anon: [schemaName] },
  };
  await fs.writeFile(path.join(moduleDir, "module.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  created.push("module.json");

  // build/<schema>.ddl.sql (DDL placeholder)
  await fs.writeFile(
    path.join(moduleDir, "build", `${schemaName}.ddl.sql`),
    `-- ${name} — DDL\n\nCREATE SCHEMA IF NOT EXISTS ${schemaName};\nCREATE SCHEMA IF NOT EXISTS ${schemaName}_ut;\nCREATE SCHEMA IF NOT EXISTS ${schemaName}_qa;\n`,
  );
  created.push(`build/${schemaName}.ddl.sql`);

  // build/<schema>.func.sql (pg_pack output placeholder)
  await fs.writeFile(
    path.join(moduleDir, "build", `${schemaName}.func.sql`),
    `-- Auto-generated by pg_pack (${schemaName})\n`,
  );
  created.push(`build/${schemaName}.func.sql`);

  // .mcp.json
  await fs.writeFile(
    path.join(moduleDir, ".mcp.json"),
    `${JSON.stringify(
      {
        mcpServers: {
          "plpgsql-workbench": {
            type: "http",
            url: `http://localhost:${mcpPort}/mcp`,
          },
          "workbench-msg": {
            command: "npx",
            args: ["tsx", "../../src/channel/workbench-msg.ts"],
            env: { MODULE: name },
          },
          maket: {
            type: "http",
            url: "http://localhost:3337/mcp",
          },
        },
      },
      null,
      2,
    )}\n`,
  );
  created.push(".mcp.json");

  // .claude/settings.local.json — dev-focused permissions + hooks
  await fs.writeFile(path.join(moduleDir, ".claude", "settings.local.json"), moduleClaudeSettings(name, mcpPort));
  created.push(".claude/settings.local.json");

  // CLAUDE.md
  await fs.writeFile(path.join(moduleDir, "CLAUDE.md"), moduleClaudeMd(name, schemaName, description));
  created.push("CLAUDE.md");

  return created;
}

function moduleClaudeMd(name: string, schema: string, description?: string): string {
  const desc = description ?? "Description a completer.";
  return `# ${name}

${desc}

**Depend de :** \`pgv\`

**Schemas :** \`${schema}\`, \`${schema}_ut\` (tests), \`${schema}_qa\` (seed data)

## Framework pgView

Ce module est un **module independant** du framework pgView. Ses dependances sont declarees dans \`module.json\`.

### Conventions PL/pgSQL

- \`get_*()\` → pages GET, \`post_*()\` → actions POST. Nommage = routing automatique via \`pgv.route()\`
- \`nav_items() -> jsonb\` → menu du module. Retourne \`jsonb\` (JAMAIS TABLE)
- \`brand() -> text\` → nom affiche dans la nav
- \`get_index()\` → page d'accueil du module (obligatoire)
- Parametres via query string : \`/page?p_id=42\` → \`get_page(p_id int)\`
- POST retourne raw HTML (templates \`<template data-toast>\` ou \`<template data-redirect>\`) — jamais wrappe dans \`page()\`
- Tables via \`<md>\` blocks (markdown), JAMAIS \`<table>\` HTML. \`<md data-page="20">\` pour pagination
- CSS classes \`pgv-*\`, JAMAIS de \`style="..."\` inline
- Primitives UI : \`pgv.stat()\`, \`pgv.badge()\`, \`pgv.card()\`, \`pgv.grid()\`, \`pgv.empty()\`, \`pgv.md_table()\`, \`pgv.action()\`

### Workflow dev (STRICT)

1. **DDL** → Write dans \`build/{schema}.ddl.sql\` → \`pg_schema\` pour appliquer
2. **Fonctions** → \`pg_func_set\` pour creer/modifier + \`pg_test\` pour valider
3. **Exporter** → \`pg_pack\` (→ \`build/{schema}.func.sql\`) + \`pg_func_save\` (→ \`src/\`)
4. \`pg_query\` → SELECT/DML uniquement, JAMAIS de DDL ou CREATE FUNCTION
5. JAMAIS ecrire de fonctions dans des fichiers SQL — le workbench EST l'outil de dev
6. JAMAIS editer \`build/*.func.sql\` — genere par \`pg_pack\`

### Module structure

- \`module.json\` → manifest (schemas, dependencies, extensions, sql, grants)
- \`build/\` → artefacts de deploiement (DDL + fonctions packees)
- \`src/\` → sources individuelles versionnees (pg_func_save)
- \`_ut\` schemas → tests pgTAP (\`test_*()\`)
- \`_qa\` schemas → seed data uniquement (\`seed()\`, \`clean()\`), PAS de pages

### Contenu du DDL (\`build/{schema}.ddl.sql\`) — STRICT

Le DDL contient **uniquement de la structure**. Ordre d'application des migrations :
\`\`\`
1. Extensions     → dans la migration globale, PAS dans le DDL module
2. DDL            → CREATE SCHEMA, CREATE TABLE, indexes, constraints, RLS policies
3. Functions      → pg_pack genere build/{schema}.func.sql (+ triggers attaches)
4. Grants         → pg_pack les ajoute a la fin de chaque .func.sql
5. Seed referentiel → donnees de reference dans build/{schema}.seed.sql (optionnel)
\`\`\`

**Le DDL DOIT contenir :**
- \`CREATE SCHEMA IF NOT EXISTS {schema};\`
- \`CREATE TABLE\`, \`CREATE INDEX\`, \`ALTER TABLE ... ADD CONSTRAINT\`
- \`ALTER TABLE ... ENABLE ROW LEVEL SECURITY\` + \`CREATE POLICY\`

**Le DDL NE DOIT PAS contenir :**
- \`CREATE FUNCTION\` → va dans les fonctions (pg_func_set → pg_pack)
- \`CREATE TRIGGER\` → pg_pack l'attache apres la fonction trigger dans .func.sql
- \`GRANT\` → pg_pack les ajoute a la fin de chaque .func.sql
- \`INSERT INTO\` → les donnees de reference vont dans \`build/{schema}.seed.sql\`
- Donnees de demo → vont dans \`{schema}_qa.seed()\`

### Donnees de reference (\`build/{schema}.seed.sql\`)

Certains modules ont des donnees de reference necessaires au fonctionnement :
- Plan comptable (ledger), categories par defaut (catalog), cles i18n (pgv)
- Ces donnees sont **partagees entre tous les tenants** (\`tenant_id IS NULL\` ou omis)
- Elles vivent dans \`build/{schema}.seed.sql\`, PAS dans le DDL
- Convention : \`INSERT ... ON CONFLICT DO NOTHING\` (idempotent)
- Ce fichier est reference dans \`module.json\` sql array, APRES le .func.sql

### Communication inter-modules

- \`pg_msg_inbox module:${name}\` → lire les messages entrants
- \`pg_msg\` → envoyer un message a un autre module
- Chaque module est autonome — ne jamais modifier les fonctions d'un autre module

## i18n

Le framework utilise \`pgv.t(key)\` pour l'internationalisation. Chaque module doit :
1. Créer \`${name}.i18n_seed()\` — INSERT INTO pgv.i18n(lang, key, value) les traductions FR
2. Clés namespaced : \`${name}.nav_xxx\`, \`${name}.title_xxx\`, \`${name}.btn_xxx\`, etc.
3. Utiliser \`pgv.t('${name}.xxx')\` dans nav_items(), brand(), et toutes les fonctions get_*/post_*
4. \`ON CONFLICT DO NOTHING\` dans le seed

## QA Seed Data

Le schema \`${name}_qa\` contient uniquement \`seed()\` et \`clean()\` — PAS de pages.
- \`${name}_qa.seed()\` — INSERT données démo réalistes
- \`${name}_qa.clean()\` — DELETE dans l'ordre inverse des FK
- \`ON CONFLICT DO NOTHING\`, penser multi-tenant (\`current_setting('app.tenant_id', true)\`)

## Workflow agent

1. Au démarrage ou quand on te dit "go" : **toujours lire \`pg_msg_inbox module:${name}\`**
2. Traiter les messages par priorité (HIGH d'abord)
3. Ne pas résoudre un message tant que la tâche n'est pas vérifiée
4. Après chaque tâche : \`pg_pack schemas: ${name},${name}_ut,${name}_qa\` (les 3 schemas)
5. Puis \`pg_func_save target: plpgsql://${name}\` + \`plpgsql://${name}_ut\` + \`plpgsql://${name}_qa\`

## Documentation intégrée

Le workbench embarque de la documentation accessible via \`pg_doc\` :
- \`pg_doc topic:testing\` — Guide pgTAP : conventions test_*(), assertions, patterns
- \`pg_doc topic:data-convention\` — Convention data_*() : cursor pagination, FTS, pgv.table()
- \`pg_doc topic:coverage\` — Guide couverture de code

## Gotchas

- **tenant_id** : toujours \`PERFORM set_config('app.tenant_id', 'test', true)\` au début de chaque test
- **pg_test** : découvre les fonctions \`test_*()\` dans le schema \`_ut\` — utiliser \`pg_test schema:${name}_ut\`
- (a completer au fil du developpement)

## Premier demarrage

Lire \`pg_msg_inbox module:${name}\` pour les instructions d'implementation detaillees.
Consulter crm, quote, ledger comme reference pour les patterns pgView.
`;
}

function moduleClaudeSettings(moduleName: string, mcpPort: number): string {
  return `${JSON.stringify(
    {
      permissions: {
        allow: [
          "Bash(git:*)",
          "mcp__plpgsql-workbench__pg_query",
          "mcp__plpgsql-workbench__pg_get",
          "mcp__plpgsql-workbench__pg_func_set",
          "mcp__plpgsql-workbench__pg_func_edit",
          "mcp__plpgsql-workbench__pg_func_save",
          "mcp__plpgsql-workbench__pg_func_load",
          "mcp__plpgsql-workbench__pg_test",
          "mcp__plpgsql-workbench__pg_explain",
          "mcp__plpgsql-workbench__pg_search",
          "mcp__plpgsql-workbench__pg_schema",
          "mcp__plpgsql-workbench__pg_pack",
          "mcp__plpgsql-workbench__pg_coverage",
          "mcp__plpgsql-workbench__pg_doc",
          "mcp__plpgsql-workbench__pg_msg",
          "mcp__plpgsql-workbench__pg_msg_inbox",
          "mcp__plpgsql-workbench__pg_preview",
        ],
      },
      enableAllProjectMcpServers: true,
      enabledMcpjsonServers: ["plpgsql-workbench"],
      hooks: {
        SessionStart: [
          {
            matcher: "startup|resume",
            hooks: [
              {
                type: "http",
                url: `http://localhost:${mcpPort}/hooks/${moduleName}/session`,
                timeout: 5,
              },
            ],
          },
        ],
        PreToolUse: [
          {
            matcher:
              "mcp__plpgsql-workbench__pg_query|mcp__plpgsql-workbench__pg_func_set|mcp__plpgsql-workbench__pg_func_edit|Write|Edit",
            hooks: [
              {
                type: "http",
                url: `http://localhost:${mcpPort}/hooks/${moduleName}`,
                timeout: 5,
              },
            ],
          },
        ],
      },
    },
    null,
    2,
  )}\n`;
}
