/**
 * pgm supabase — sync module SQL to Supabase migrations.
 *
 * Reads module manifests, resolves dependencies, generates numbered
 * migration files in supabase/migrations/ from build/*.sql files.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { loadManifest, resolve } from "./resolver.js";

export interface SyncResult {
  migrations: string[];
  modules: string[];
}

/**
 * Generate Supabase migrations from module build files.
 *
 * @param wsRoot - workspace root (contains modules/ and supabase/)
 * @param moduleNames - modules to include (resolved with dependencies)
 * @param prefix - timestamp prefix for migration files (default: auto-generate)
 */
export async function syncToSupabase(wsRoot: string, moduleNames: string[], prefix?: string): Promise<SyncResult> {
  const modulesDir = path.join(wsRoot, "modules");
  const migrationsDir = path.join(wsRoot, "supabase", "migrations");

  // Ensure migrations dir exists
  await fs.mkdir(migrationsDir, { recursive: true });

  // Resolve dependency order
  const plan = await resolve(modulesDir, moduleNames);
  const result: SyncResult = { migrations: [], modules: [] };

  // Collect all extensions needed
  const extensions = new Set<string>();
  for (const mod of plan.order) {
    for (const ext of mod.extensions) {
      extensions.add(ext);
    }
  }

  // Also check if any module uses pgv_search FTS config (needs unaccent)
  for (const mod of plan.order) {
    const manifest = await loadManifest(modulesDir, mod.name);
    for (const sqlFile of manifest.sql) {
      try {
        const content = await fs.readFile(path.join(modulesDir, mod.name, sqlFile), "utf-8");
        if (content.includes("pgv_search")) {
          extensions.add("unaccent");
        }
      } catch {}
    }
  }

  const ts = prefix ?? generateTimestamp();
  let seq = 0;

  // Migration 0: Extensions (filter dev-only)
  const devOnlyExtensions = new Set(["plpgsql_check", "pgtap"]);
  const prodExtensions = Array.from(extensions).filter((ext) => !devOnlyExtensions.has(ext));

  if (prodExtensions.length > 0 || extensions.has("unaccent")) {
    const extSql = prodExtensions.map((ext) => `CREATE EXTENSION IF NOT EXISTS ${ext};`).join("\n");

    // Add pgv_search FTS config only if pgv module is NOT in the sync list
    // (pgv.ddl.sql creates it already — avoid double creation)
    const pgvIncluded = plan.order.some((m) => m.name === "pgv");
    let ftsSql = "";
    if (extensions.has("unaccent") && !pgvIncluded) {
      ftsSql = `
-- FTS config: french + unaccent (shared by asset, document, etc.)
DO $$ BEGIN
  CREATE TEXT SEARCH CONFIGURATION pgv_search (COPY = french);
  ALTER TEXT SEARCH CONFIGURATION pgv_search
    ALTER MAPPING FOR hword, hword_part, word
    WITH unaccent, french_stem;
EXCEPTION WHEN unique_violation OR duplicate_object THEN NULL;
END $$;
`;
    }

    const filename = `${ts}${String(seq).padStart(2, "0")}_extensions.sql`;
    await fs.writeFile(
      path.join(migrationsDir, filename),
      `-- Auto-generated by pgm supabase sync\n-- Extensions required by: ${moduleNames.join(", ")}\n\n${extSql}\n${ftsSql}`,
    );
    result.migrations.push(filename);
    seq++;
  }

  // Migrations per module (DDL then functions, in dependency order)
  for (const mod of plan.order) {
    // Skip pgv — it's framework, not deployed to Supabase (unless explicitly requested)
    if (mod.name === "pgv" && !moduleNames.includes("pgv")) continue;

    const manifest = await loadManifest(modulesDir, mod.name);
    result.modules.push(mod.name);

    for (const sqlFile of manifest.sql) {
      const srcPath = path.join(modulesDir, mod.name, sqlFile);
      try {
        const content = await fs.readFile(srcPath, "utf-8");
        if (content.trim().length < 50) continue; // skip placeholder files

        const basename = path.basename(sqlFile);

        // Skip standalone _ut and _qa DDL files
        if (basename.includes("_ut.") || basename.includes("_qa.")) continue;

        // No role adaptation needed — dev and prod use same roles (anon, authenticated)
        // Remove dev-only extensions that may not exist on Supabase
        // Strip _ut and _qa function blocks from .func.sql files
        const adapted = content
          .replace(/CREATE EXTENSION IF NOT EXISTS plpgsql_check[^;]*;/g, "-- plpgsql_check (dev only)")
          .replace(/CREATE EXTENSION IF NOT EXISTS pgtap[^;]*;/g, "-- pgtap (dev only)");

        // Adapt tenant_id default for Supabase Auth
        // current_setting('app.tenant_id', true) → auth.uid()::text for production
        // Keep as-is for now — tenant_id will be set via RLS or app config

        const filename = `${ts}${String(seq).padStart(2, "0")}_${mod.name}_${basename}`;
        await fs.writeFile(
          path.join(migrationsDir, filename),
          `-- Auto-generated by pgm supabase sync\n-- Module: ${mod.name}@${mod.version}\n-- Source: modules/${mod.name}/${sqlFile}\n\n${adapted}`,
        );
        result.migrations.push(filename);
        seq++;
      } catch {
        // File doesn't exist or can't be read — skip
      }
    }
  }

  return result;
}

/**
 * Clean generated migrations (remove all auto-generated files).
 */
export async function cleanSupabaseMigrations(wsRoot: string): Promise<number> {
  const migrationsDir = path.join(wsRoot, "supabase", "migrations");
  let count = 0;
  try {
    const files = await fs.readdir(migrationsDir);
    for (const f of files) {
      const content = await fs.readFile(path.join(migrationsDir, f), "utf-8");
      if (content.includes("Auto-generated by pgm supabase sync")) {
        await fs.unlink(path.join(migrationsDir, f));
        count++;
      }
    }
  } catch {}
  return count;
}

function generateTimestamp(): string {
  const now = new Date();
  return [
    now.getFullYear(),
    String(now.getMonth() + 1).padStart(2, "0"),
    String(now.getDate()).padStart(2, "0"),
    String(now.getHours()).padStart(2, "0"),
    String(now.getMinutes()).padStart(2, "0"),
    String(now.getSeconds()).padStart(2, "0"),
  ].join("");
}
