/**
 * pgm installer — copies module SQL + assets into an app directory
 * with proper slot numbering and ordering.
 * Generates pgv-modules.js for Alpine.js component loading.
 */

import fs from "fs/promises";
import path from "path";
import type { InstallPlan } from "./resolver.js";

// --- Slot assignment ---
// 00 = extensions (pgv)
// 01 = roles (app-specific, never from a module)
// 02 = pgv framework SQL
// 05+ = other modules (one slot per module)

const PGV_SLOT = 2;
const MODULE_SLOT_START = 5;

interface CopyResult {
  module: string;
  version: string;
  files: string[];
}

export async function installModules(
  modulesDir: string,
  appDir: string,
  plan: InstallPlan,
): Promise<CopyResult[]> {
  const results: CopyResult[] = [];
  let nextSlot = MODULE_SLOT_START;
  const allScripts: string[] = [];
  const allStyles: string[] = [];

  for (const manifest of plan.order) {
    const moduleDir = path.join(modulesDir, manifest.name);
    const files: string[] = [];

    // --- SQL files ---
    for (const sqlFile of manifest.sql) {
      const src = path.join(moduleDir, sqlFile);
      const basename = path.basename(sqlFile);

      if (!await fileExists(src)) {
        continue;
      }

      let targetName: string;
      const slot = manifest.name === "pgv"
        ? String(PGV_SLOT).padStart(2, "0")
        : String(nextSlot).padStart(2, "0");
      // basename is already schema-prefixed (e.g. cad.ddl.sql, pgv.func.sql)
      targetName = `${slot}-${basename}`;

      await fs.copyFile(src, path.join(appDir, "sql", targetName));
      files.push(`sql/${targetName}`);
    }

    // --- Frontend assets ---
    const frontendAssets = manifest.assets?.frontend ?? [];
    for (const assetFile of frontendAssets) {
      const src = path.join(moduleDir, assetFile);
      const basename = path.basename(assetFile);

      if (!await fileExists(src)) {
        continue;
      }

      await fs.copyFile(src, path.join(appDir, "frontend", basename));
      files.push(`frontend/${basename}`);
    }

    // --- Scripts (Alpine.js components) ---
    const scripts = manifest.assets?.scripts ?? [];
    for (const scriptFile of scripts) {
      const src = path.join(moduleDir, scriptFile);
      const basename = path.basename(scriptFile);

      if (!await fileExists(src)) {
        continue;
      }

      await fs.copyFile(src, path.join(appDir, "frontend", basename));
      files.push(`frontend/${basename}`);
      allScripts.push(basename);
    }

    // --- Styles (module CSS) ---
    const styles = manifest.assets?.styles ?? [];
    for (const styleFile of styles) {
      const src = path.join(moduleDir, styleFile);
      const basename = path.basename(styleFile);

      if (!await fileExists(src)) {
        continue;
      }

      await fs.copyFile(src, path.join(appDir, "frontend", basename));
      files.push(`frontend/${basename}`);
      allStyles.push(basename);
    }

    results.push({ module: manifest.name, version: manifest.version, files });

    if (manifest.name !== "pgv") {
      nextSlot++;
    }
  }

  // --- Generate pgv-modules.js ---
  if (allScripts.length > 0 || allStyles.length > 0) {
    await generateModulesLoader(appDir, allScripts, allStyles);
    results.push({
      module: "pgm",
      version: "",
      files: ["frontend/pgv-modules.js (generated)"],
    });
  }

  // --- Generate 00-extensions.sql ---
  await generateExtensions(appDir, plan);

  // --- Generate .env with PGRST_DB_SCHEMAS ---
  await generateEnv(appDir, plan);

  // --- Generate 99-grants.sql (PostgREST schema access) ---
  await generateGrants(appDir, plan);

  return results;
}

// --- pgv-modules.js generator ---

async function generateModulesLoader(
  appDir: string,
  scripts: string[],
  styles: string[],
): Promise<void> {
  const lines: string[] = [];
  lines.push("// Auto-generated by pgm install — DO NOT EDIT");
  lines.push("(function() {");

  // Load styles
  for (const style of styles) {
    lines.push(`  var l = document.createElement('link');`);
    lines.push(`  l.rel = 'stylesheet';`);
    lines.push(`  l.href = '/${style}';`);
    lines.push(`  document.head.appendChild(l);`);
  }

  // Load scripts
  for (const script of scripts) {
    lines.push(`  var s = document.createElement('script');`);
    lines.push(`  s.src = '/${script}';`);
    lines.push(`  document.head.appendChild(s);`);
  }

  lines.push("})();");

  await fs.writeFile(
    path.join(appDir, "frontend", "pgv-modules.js"),
    lines.join("\n") + "\n",
  );
}

// --- 00-extensions.sql generator ---

async function generateExtensions(appDir: string, plan: InstallPlan): Promise<void> {
  const seen = new Set<string>();
  const extensions: string[] = [];
  for (const manifest of plan.order) {
    for (const ext of manifest.extensions) {
      if (!seen.has(ext)) {
        seen.add(ext);
        extensions.push(ext);
      }
    }
  }
  if (extensions.length === 0) return;

  const lines: string[] = [];
  lines.push("-- Auto-generated by pgm install — DO NOT EDIT");
  for (const ext of extensions) {
    lines.push(`CREATE EXTENSION IF NOT EXISTS "${ext}";`);
  }
  await fs.writeFile(
    path.join(appDir, "sql", "00-extensions.sql"),
    lines.join("\n") + "\n",
  );
}

// --- .env generator (PGRST_DB_SCHEMAS) ---

async function generateEnv(appDir: string, plan: InstallPlan): Promise<void> {
  const schemas: string[] = [];
  for (const manifest of plan.order) {
    const pub = manifest.schemas.public;
    if (!pub) continue;
    schemas.push(pub);
    // Include _ut, _qa variants for dev/test access via PostgREST
    schemas.push(`${pub}_ut`);
    const qa = manifest.schemas.qa;
    if (qa) schemas.push(qa);
  }
  // Sort: pgv* first, then alphabetical
  schemas.sort((a, b) => {
    const aIsPgv = a.startsWith("pgv") ? 0 : 1;
    const bIsPgv = b.startsWith("pgv") ? 0 : 1;
    if (aIsPgv !== bIsPgv) return aIsPgv - bIsPgv;
    return a.localeCompare(b);
  });
  await fs.writeFile(
    path.join(appDir, ".env"),
    `PGRST_DB_SCHEMAS=${schemas.join(",")}\n`,
  );
}

// --- 99-grants.sql generator (PostgREST access) ---

async function generateGrants(appDir: string, plan: InstallPlan): Promise<void> {
  const lines: string[] = [];
  lines.push("-- Auto-generated by pgm install — DO NOT EDIT");
  lines.push("-- GRANTs for PostgREST (web_anon access to module schemas + functions)\n");

  for (const manifest of plan.order) {
    for (const [role, schemas] of Object.entries(manifest.grants ?? {})) {
      for (const schema of schemas) {
        lines.push(`GRANT USAGE ON SCHEMA "${schema}" TO "${role}";`);
        lines.push(`GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "${schema}" TO "${role}";`);
      }
    }
  }

  await fs.writeFile(
    path.join(appDir, "sql", "99-grants.sql"),
    lines.join("\n") + "\n",
  );
}

// --- Helpers ---

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}
