/**
 * pgm installer — copies module SQL + assets into an app directory
 * with proper slot numbering and ordering.
 * Generates pgv-modules.js for Alpine.js component loading.
 */

import fs from "fs/promises";
import path from "path";
import type { InstallPlan } from "./resolver.js";

// --- Slot assignment ---
// 00 = extensions (pgv)
// 01 = roles (app-specific, never from a module)
// 02 = pgv framework SQL
// 05+ = other modules (one slot per module)

const PGV_SLOT = 2;
const MODULE_SLOT_START = 5;

interface CopyResult {
  module: string;
  version: string;
  files: string[];
}

export async function installModules(
  modulesDir: string,
  appDir: string,
  plan: InstallPlan,
): Promise<CopyResult[]> {
  const results: CopyResult[] = [];
  let nextSlot = MODULE_SLOT_START;
  const allScripts: string[] = [];
  const allStyles: string[] = [];

  for (const manifest of plan.order) {
    const moduleDir = path.join(modulesDir, manifest.name);
    const files: string[] = [];

    // --- SQL files ---
    for (const sqlFile of manifest.sql) {
      const src = path.join(moduleDir, sqlFile);
      const basename = path.basename(sqlFile);

      if (!await fileExists(src)) {
        continue;
      }

      let targetName: string;
      if (manifest.name === "pgv") {
        // pgv has reserved slots
        switch (basename) {
          case "00-extensions.sql": targetName = "00-extensions.sql"; break;
          case "pgv.sql":           targetName = "02-pgv.sql"; break;
          default:                  targetName = `0${PGV_SLOT}-${basename}`; break;
        }
      } else {
        // Other modules get their slot
        const slot = String(nextSlot).padStart(2, "0");
        switch (basename) {
          case "00-extensions.sql": targetName = `${slot}-${manifest.name}-extensions.sql`; break;
          default:                  targetName = `${slot}-${manifest.name}-${basename}`; break;
        }
      }

      await fs.copyFile(src, path.join(appDir, "sql", targetName));
      files.push(`sql/${targetName}`);
    }

    // --- Frontend assets ---
    const frontendAssets = manifest.assets?.frontend ?? [];
    for (const assetFile of frontendAssets) {
      const src = path.join(moduleDir, assetFile);
      const basename = path.basename(assetFile);

      if (!await fileExists(src)) {
        continue;
      }

      await fs.copyFile(src, path.join(appDir, "frontend", basename));
      files.push(`frontend/${basename}`);
    }

    // --- Scripts (Alpine.js components) ---
    const scripts = manifest.assets?.scripts ?? [];
    for (const scriptFile of scripts) {
      const src = path.join(moduleDir, scriptFile);
      const basename = path.basename(scriptFile);

      if (!await fileExists(src)) {
        continue;
      }

      await fs.copyFile(src, path.join(appDir, "frontend", basename));
      files.push(`frontend/${basename}`);
      allScripts.push(basename);
    }

    // --- Styles (module CSS) ---
    const styles = manifest.assets?.styles ?? [];
    for (const styleFile of styles) {
      const src = path.join(moduleDir, styleFile);
      const basename = path.basename(styleFile);

      if (!await fileExists(src)) {
        continue;
      }

      await fs.copyFile(src, path.join(appDir, "frontend", basename));
      files.push(`frontend/${basename}`);
      allStyles.push(basename);
    }

    results.push({ module: manifest.name, version: manifest.version, files });

    if (manifest.name !== "pgv") {
      nextSlot++;
    }
  }

  // --- Generate pgv-modules.js ---
  await generateModulesLoader(appDir, allScripts, allStyles);
  if (allScripts.length > 0 || allStyles.length > 0) {
    results.push({
      module: "pgm",
      version: "",
      files: ["frontend/pgv-modules.js (generated)"],
    });
  }

  return results;
}

// --- pgv-modules.js generator ---

async function generateModulesLoader(
  appDir: string,
  scripts: string[],
  styles: string[],
): Promise<void> {
  const lines: string[] = [];
  lines.push("// Auto-generated by pgm install — DO NOT EDIT");
  lines.push("(function() {");

  // Load styles
  for (const style of styles) {
    lines.push(`  var l = document.createElement('link');`);
    lines.push(`  l.rel = 'stylesheet';`);
    lines.push(`  l.href = '/${style}';`);
    lines.push(`  document.head.appendChild(l);`);
  }

  // Load scripts
  for (const script of scripts) {
    lines.push(`  var s = document.createElement('script');`);
    lines.push(`  s.src = '/${script}';`);
    lines.push(`  document.head.appendChild(s);`);
  }

  lines.push("})();");

  await fs.writeFile(
    path.join(appDir, "frontend", "pgv-modules.js"),
    lines.join("\n") + "\n",
  );
}

// --- Helpers ---

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}
