import { z } from "zod";
import type { DbClient } from "../../connection.js";
import type { ToolHandler, WithClient } from "../../container.js";
import { text } from "../../helpers.js";
import fs from "fs/promises";
import path from "path";

interface FuncRow {
  schema: string;
  name: string;
  lang: string;
  ddl: string;
}

async function querySchemaFunctions(
  client: DbClient,
  schema: string,
): Promise<FuncRow[]> {
  const { rows } = await client.query<FuncRow>(
    `SELECT n.nspname AS schema, p.proname AS name, l.lanname AS lang,
            pg_get_functiondef(p.oid) AS ddl
     FROM pg_proc p
     JOIN pg_namespace n ON n.oid = p.pronamespace
     JOIN pg_language l ON l.oid = p.prolang
     WHERE n.nspname = $1
       AND l.lanname IN ('sql', 'plpgsql')
       AND NOT EXISTS (
         SELECT 1 FROM pg_depend d
         JOIN pg_extension e ON e.oid = d.refobjid
         WHERE d.objid = p.oid AND d.deptype = 'e'
       )
     ORDER BY
       CASE l.lanname WHEN 'sql' THEN 0 ELSE 1 END,
       p.proname, p.oid`,
    [schema],
  );
  return rows;
}

export function createPackTool({ withClient }: {
  withClient: WithClient;
}): ToolHandler {
  return {
    metadata: {
      name: "pg_pack",
      description:
        "Export schemas into a single consolidated SQL init file.\n" +
        "Includes CREATE SCHEMA + all functions (sql first, then plpgsql) + GRANT.\n" +
        "Use for docker-compose init scripts or framework distribution.",
      schema: z.object({
        schemas: z.string().describe("Comma-separated schema names. Ex: pgv,pgv_ut"),
        path: z.string().describe("Output file path (.sql). Ex: uxlab/sql/02-pgv.sql"),
        role: z.string().optional().describe("Role for GRANT EXECUTE (default: web_anon)"),
      }),
    },
    handler: async (args) => {
      const schemas = (args.schemas as string).split(",").map((s) => s.trim()).filter(Boolean);
      const outFile = args.path as string;
      const role = (args.role as string) ?? "web_anon";

      if (schemas.length === 0) return text("problem: no schemas specified");

      const resolved = path.isAbsolute(outFile)
        ? outFile
        : path.resolve(process.cwd(), outFile);

      return withClient(async (client) => {
        const sections: string[] = [];
        let totalFunctions = 0;

        for (const schema of schemas) {
          const fns = await querySchemaFunctions(client, schema);

          sections.push(`-- Schema: ${schema}`);
          sections.push(`CREATE SCHEMA IF NOT EXISTS ${schema};`);
          sections.push("");

          if (fns.length === 0) {
            sections.push(`-- (no functions)`);
          } else {
            for (const fn of fns) {
              const ddl = fn.ddl.trimEnd();
              sections.push(ddl.endsWith(";") ? ddl : ddl + ";");
              sections.push("");
            }
            totalFunctions += fns.length;
          }

          sections.push(`GRANT USAGE ON SCHEMA ${schema} TO ${role};`);
          sections.push(`GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ${schema} TO ${role};`);
          sections.push("");
        }

        const content = `-- Auto-generated by pg_pack (${schemas.join(", ")})\n-- ${new Date().toISOString().slice(0, 10)}\n\n${sections.join("\n")}`;

        await fs.mkdir(path.dirname(resolved), { recursive: true });
        await fs.writeFile(resolved, content, "utf-8");

        const parts: string[] = [];
        parts.push(`✓ packed ${totalFunctions} functions from ${schemas.length} schema(s) -> ${outFile}`);
        parts.push(`completeness: full`);
        parts.push("");
        for (const s of schemas) {
          const count = (await querySchemaFunctions(client, s)).length;
          parts.push(`  ${s}: ${count} functions`);
        }
        return text(parts.join("\n"));
      });
    },
  };
}
